### ISSUE TITLE
Geojson fields truncated

### ISSUE THREAD

**Issue by melhk** [enermaps/enermaps#264]
Geojson fields larger than 255 characters are truncated. In these case we loose information about "fields" "variables" or "units", etc. and we no longer have valid json:

![11](https://user-images.githubusercontent.com/11057275/127648937-9919d983-55f5-4f01-a214-2fd459c1ab63.PNG)

![2](https://user-images.githubusercontent.com/11057275/127648950-3d8f9756-64a1-4e3b-8c2a-a24158af9ae2.PNG)

![27](https://user-images.githubusercontent.com/11057275/127649339-543d92e8-4166-4259-bdb2-c115f8d2554f.PNG)

**Comment by gperonato** [comment]
I think we discussed this before. This is likely due to the conversion to SHP, which has a strict limit on the field size. I was recommending to switch to another file format (e.g. directly GeoJSON).
There is no easy solution to this. What I could do is to make each field contained in the 'variables' and 'fields` objects  standalone fields, i.e. at the same level of the 'z' field.
The only problem, would be to identify which are 'fields' and which 'variables'... I could use a prefix for that. The 250 character limit might still be a problem in some cases, I have to check.
However would that work for you?

**Comment by melhk** [comment]
Yes this has already been discussed, but at that point you told me that the truncated fields contained metadata that were not particularly important and that this problem could be put aside.
I am not sure of the best solution. If we make 'variables' and 'fields' standalone fields, these fields will also be truncated, right?
And I don't really know why we are using shapefiles instead of geojson since I wasn't there at the start of the project, but I imagine that there is a reason. Maybe you know it?

**Comment by gperonato** [comment]
I don't see any particular advantage for using shapefiles instead of more recent open formats (notably GeoPackage), especially that these are handled in the backend and not by the end-user (who might be more comfortable in dealing with a legacy format like shapefile).

Standalone fields are very unlikely to be truncated, as the information for one single field like 'name_country`in one of your screenshots is only a few characters long. So this could be a workaround if we really want to use shapefiles, but I would need to check the SQL function that creates the geojson to see whether this is possible.

I don't think I have suggested putting aside any metadata.
Only as a provisional solution for the September demo, it might be acceptable to have truncated metadata.

So here is what I suggest:
in the backend, you make sure that each field in the shapefile is a valid json object. If not (because is truncated as in you examples), you make it valid adjusting it (e.g. removing incomplete fields and adding the final `}`). This could be acceptable for an initial demo.
Meanwhile, I will check how to make standalone fields in the GeoJSON AIPI output, so that they it be converted to shp without truncated fields.

**Comment by melhk** [comment]
Yes for the September demo the truncated metadata can be acceptable. But I don't think your suggestion would work, it's indeed not a simple problem: 

I cannot "repair the json once it is transformed into shapefile because I can not read an write into a shapefile, and fixing the json can be complicated. For example, we must know how many brackets are missing and where we have to had them again in the file.

And I am not sure that transforming the truncated fields into standalone fields would work either. If I understand correctly, the truncated fields would become field names but shapefile field names seem to be limited to 10 characters (so it's even worse). 

The best solution would be to find a way to use GeoPackage instead of shapefiles, but we must take the time to investigate this question.

**Comment by gperonato** [comment]
Yes, good point, the length of the field names is even a bigger problem...
I think it makes sense to change the format to GeoPackage, which doesn't have any limitation on this.

**Comment by Kanma** [comment]
Not an issue in the current version of the web app, shapefiles aren't used anymore.
